services:
  # Laravel Backend (PHP-FPM)
  app:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - laravel_vendor:/var/www/vendor
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: service_pro
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      APP_URL: http://localhost:8000
      BROADCAST_CONNECTION: reverb
      REVERB_HOST: reverb
      REVERB_PORT: 8085
      REVERB_SCHEME: http
    depends_on:
      - db

  # Reverb WebSocket Server (Service Dédié)
  reverb:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: laravel_reverb
    restart: unless-stopped
    working_dir: /var/www
    # Commande spécifique pour lancer le serveur WebSocket
    command: php artisan reverb:start --host=0.0.0.0 --port=8085
    ports:
      - "8085:8085"
    volumes:
      - ./backend:/var/www
      - laravel_vendor:/var/www/vendor
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: service_pro
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      REVERB_APP_ID: ${REVERB_APP_ID:-637618}
      REVERB_APP_KEY: ${REVERB_APP_KEY:-rniokldezyhcx1fxn6yy}
      REVERB_APP_SECRET: ${REVERB_APP_SECRET:-gxc2a9mpdezzxuaj124p}
      REVERB_HOST: "0.0.0.0"
      REVERB_PORT: 8085
      REVERB_SCHEME: http
    depends_on:
      - db
      - app

  # Nginx for Backend (serves API)
  backend-web:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  # Database (MySQL 8.0)
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    # Optimisation mémoire pour EC2 Free Tier
    command: --performance-schema=OFF --innodb-buffer-pool-size=64M
    environment:
      MYSQL_DATABASE: service_pro
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "33060:3306"

  # Frontend (Vue.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend-web
      - reverb

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
      PMA_ARBITRARY: 1
    depends_on:
      - db

volumes:
  dbdata:
  laravel_vendor:
